### PR TITLE
Phone number bug fix

### LINKED ISSUE #128: [PE-D][Tester A] Phone number digits does not have a limit
-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: ChinJunAn/ped#7

### PR DESCRIPTION
**Pull request by evanpy**
Phone number now accepts only digits with length ranging 7 to 15 inclusive which resolves #128.

### CODE REVIEW

File: src/test/java/seedu/address/model/person/PhoneTest.java [hunk 1]
```diff
@@ -27,14 +27,15 @@ public void isValidPhone() {
...
         assertFalse(Phone.isValidPhone("phone")); // non-numeric
         assertFalse(Phone.isValidPhone("9011p041")); // alphabets within digits
         assertFalse(Phone.isValidPhone("9312 1534")); // spaces within digits
 
         // valid phone numbers
-        assertTrue(Phone.isValidPhone("911")); // exactly 3 numbers
+        assertTrue(Phone.isValidPhone("1234567")); // exactly 7 numbers
         assertTrue(Phone.isValidPhone("93121534"));
-        assertTrue(Phone.isValidPhone("124293842033123")); // long phone numbers
+        assertTrue(Phone.isValidPhone("123456789123456")); // exactly 15 numbers
```
Comment (WesleyBLDC) [inline src/test/java/seedu/address/model/person/PhoneTest.java:39]: whats the rationale for having a range? international numbers? 

else everything looks good.

**Review by WesleyBLDC — APPROVED** [review]
LGTM
